version: 0.0
os: linux
#files:
#  - source: /main.go
#    destination: /home/ec2-user/httpapi/
    
hooks:
  BeforeInstall:
    - location: httpapi/install_dependencies.sh
      timeout: 300
      runas: root
    - location: httpapi/gobuild.sh
      timeout: 300
      runas: root
    - location: httpapi/starthttpapi.sh
      timeout: 300
      runas: root
 # ApplicationStop:
 #   - location: httpapi/killhttpapi.sh
 #     timeout: 300
 #     runas: root
