version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/httpapi
    
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
    - location: gobuild.sh
      timeout: 300
      runas: root
    - location: starthttpapi.sh
      timeout: 300
      runas: root
 # ApplicationStop:
 #   - location: httpapi/killhttpapi.sh
 #     timeout: 300
 #     runas: root
